// HTTP Status Codes
export const HTTP_STATUS = {
  // Success
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,

  // Client Errors
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,

  // Server Errors
  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
} as const;

// Application Error Codes
export const ERROR_CODES = {
  // Authentication Errors
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",
  INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",

  // Validation Errors
  VALIDATION_ERROR: "VALIDATION_ERROR",
  REQUIRED_FIELD_MISSING: "REQUIRED_FIELD_MISSING",
  INVALID_EMAIL_FORMAT: "INVALID_EMAIL_FORMAT",
  INVALID_PASSWORD_FORMAT: "INVALID_PASSWORD_FORMAT",
  PASSWORD_TOO_WEAK: "PASSWORD_TOO_WEAK",
  PASSWORDS_DO_NOT_MATCH: "PASSWORDS_DO_NOT_MATCH",
  INVALID_INPUT_FORMAT: "INVALID_INPUT_FORMAT",
  VALUE_OUT_OF_RANGE: "VALUE_OUT_OF_RANGE",

  // User Management Errors
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  EMAIL_ALREADY_IN_USE: "EMAIL_ALREADY_IN_USE",
  USERNAME_ALREADY_TAKEN: "USERNAME_ALREADY_TAKEN",
  USER_CREATION_FAILED: "USER_CREATION_FAILED",
  USER_UPDATE_FAILED: "USER_UPDATE_FAILED",
  USER_DELETION_FAILED: "USER_DELETION_FAILED",

  // Resource Errors
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  RESOURCE_ALREADY_EXISTS: "RESOURCE_ALREADY_EXISTS",
  RESOURCE_CREATION_FAILED: "RESOURCE_CREATION_FAILED",
  RESOURCE_UPDATE_FAILED: "RESOURCE_UPDATE_FAILED",
  RESOURCE_DELETION_FAILED: "RESOURCE_DELETION_FAILED",
  RESOURCE_ACCESS_DENIED: "RESOURCE_ACCESS_DENIED",

  // Database Errors
  DATABASE_CONNECTION_ERROR: "DATABASE_CONNECTION_ERROR",
  DATABASE_QUERY_ERROR: "DATABASE_QUERY_ERROR",
  DATABASE_CONSTRAINT_VIOLATION: "DATABASE_CONSTRAINT_VIOLATION",
  DATABASE_TIMEOUT: "DATABASE_TIMEOUT",

  // File Upload Errors
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
  FILE_UPLOAD_FAILED: "FILE_UPLOAD_FAILED",
  FILE_NOT_FOUND: "FILE_NOT_FOUND",
  STORAGE_QUOTA_EXCEEDED: "STORAGE_QUOTA_EXCEEDED",

  // Network & External Service Errors
  NETWORK_ERROR: "NETWORK_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  EXTERNAL_API_ERROR: "EXTERNAL_API_ERROR",
  TIMEOUT_ERROR: "TIMEOUT_ERROR",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

  // System Errors
  INTERNAL_ERROR: "INTERNAL_ERROR",
  CONFIGURATION_ERROR: "CONFIGURATION_ERROR",
  MAINTENANCE_MODE: "MAINTENANCE_MODE",
  FEATURE_DISABLED: "FEATURE_DISABLED",

  // Business Logic Errors
  BUSINESS_RULE_VIOLATION: "BUSINESS_RULE_VIOLATION",
  OPERATION_NOT_ALLOWED: "OPERATION_NOT_ALLOWED",
  INVALID_STATE: "INVALID_STATE",
  DEPENDENCY_ERROR: "DEPENDENCY_ERROR",
} as const;

// Success Codes
export const SUCCESS_CODES = {
  // Authentication Success
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  REGISTRATION_SUCCESS: "REGISTRATION_SUCCESS",
  PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS",
  EMAIL_VERIFIED: "EMAIL_VERIFIED",

  // User Management Success
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_DELETED: "USER_DELETED",
  PROFILE_UPDATED: "PROFILE_UPDATED",

  // Resource Success
  RESOURCE_CREATED: "RESOURCE_CREATED",
  RESOURCE_UPDATED: "RESOURCE_UPDATED",
  RESOURCE_DELETED: "RESOURCE_DELETED",
  RESOURCE_RETRIEVED: "RESOURCE_RETRIEVED",

  // Operation Success
  OPERATION_COMPLETED: "OPERATION_COMPLETED",
  DATA_SAVED: "DATA_SAVED",
  EMAIL_SENT: "EMAIL_SENT",
  FILE_UPLOADED: "FILE_UPLOADED",
  BACKUP_CREATED: "BACKUP_CREATED",
} as const;

// Type definitions for better TypeScript support
export type HttpStatus = (typeof HTTP_STATUS)[keyof typeof HTTP_STATUS];
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
export type SuccessCode = (typeof SUCCESS_CODES)[keyof typeof SUCCESS_CODES];
